import type { OrgRow } from '@shared/types'

export const SEED_ROWS: OrgRow[] = [
  { id: 1, parent_id: null, node_type: 'department', name: '星辰科技集团', code: 'GROUP-001', title: null, sort_order: 1 },
  { id: 2, parent_id: 1, node_type: 'department', name: '技术中心', code: 'DEPT-TECH', title: null, sort_order: 1 },
  { id: 3, parent_id: 2, node_type: 'sub_department', name: '基础架构部', code: 'SUB-INFRA', title: null, sort_order: 1 },
  { id: 4, parent_id: 3, node_type: 'team', name: '云平台组', code: 'TEAM-CLOUD', title: null, sort_order: 1 },
  { id: 5, parent_id: 4, node_type: 'employee', name: '张伟', code: 'EMP-001', title: '云平台工程师', sort_order: 1 },
  { id: 6, parent_id: 4, node_type: 'employee', name: '李娜', code: 'EMP-002', title: '云平台工程师', sort_order: 2 },
  { id: 7, parent_id: 3, node_type: 'team', name: '运维组', code: 'TEAM-SRE', title: null, sort_order: 2 },
  { id: 8, parent_id: 7, node_type: 'employee', name: '王强', code: 'EMP-003', title: '运维工程师', sort_order: 1 },
  { id: 9, parent_id: 2, node_type: 'sub_department', name: '产品研发部', code: 'SUB-PROD', title: null, sort_order: 2 },
  { id: 10, parent_id: 9, node_type: 'team', name: '前端组', code: 'TEAM-FE', title: null, sort_order: 1 },
  { id: 11, parent_id: 10, node_type: 'employee', name: '陈思', code: 'EMP-004', title: '前端工程师', sort_order: 1 },
  { id: 12, parent_id: 10, node_type: 'employee', name: '刘洋', code: 'EMP-005', title: '前端工程师', sort_order: 2 },
  { id: 13, parent_id: 9, node_type: 'team', name: '后端组', code: 'TEAM-BE', title: null, sort_order: 2 },
  { id: 14, parent_id: 13, node_type: 'employee', name: '赵敏', code: 'EMP-006', title: '后端工程师', sort_order: 1 },
  { id: 15, parent_id: 13, node_type: 'employee', name: '孙浩', code: 'EMP-007', title: '后端工程师', sort_order: 2 },
  { id: 16, parent_id: 2, node_type: 'sub_department', name: '算法实验室', code: 'SUB-ALGO', title: null, sort_order: 3 },
  { id: 17, parent_id: 16, node_type: 'team', name: '推荐算法组', code: 'TEAM-REC', title: null, sort_order: 1 },
  { id: 18, parent_id: 17, node_type: 'employee', name: '周婷', code: 'EMP-008', title: '算法工程师', sort_order: 1 },
  { id: 19, parent_id: 16, node_type: 'team', name: '视觉算法组', code: 'TEAM-CV', title: null, sort_order: 2 },
  { id: 20, parent_id: 19, node_type: 'employee', name: '吴磊', code: 'EMP-009', title: '算法工程师', sort_order: 1 },
  { id: 21, parent_id: 1, node_type: 'department', name: '业务中心', code: 'DEPT-BIZ', title: null, sort_order: 2 },
  { id: 22, parent_id: 21, node_type: 'sub_department', name: '销售部', code: 'SUB-SALES', title: null, sort_order: 1 },
  { id: 23, parent_id: 22, node_type: 'team', name: '大客户组', code: 'TEAM-KEY', title: null, sort_order: 1 },
  { id: 24, parent_id: 23, node_type: 'employee', name: '郑爽', code: 'EMP-010', title: '销售经理', sort_order: 1 },
  { id: 25, parent_id: 22, node_type: 'team', name: '渠道组', code: 'TEAM-CH', title: null, sort_order: 2 },
  { id: 26, parent_id: 25, node_type: 'employee', name: '冯巩', code: 'EMP-011', title: '销售代表', sort_order: 1 },
  { id: 27, parent_id: 21, node_type: 'sub_department', name: '市场部', code: 'SUB-MKT', title: null, sort_order: 2 },
  { id: 28, parent_id: 27, node_type: 'team', name: '品牌组', code: 'TEAM-BRAND', title: null, sort_order: 1 },
  { id: 29, parent_id: 28, node_type: 'employee', name: '褚燕', code: 'EMP-012', title: '品牌经理', sort_order: 1 },
  { id: 30, parent_id: 1, node_type: 'department', name: '职能中心', code: 'DEPT-FUNC', title: null, sort_order: 3 },
  { id: 31, parent_id: 30, node_type: 'sub_department', name: '人力资源部', code: 'SUB-HR', title: null, sort_order: 1 },
  { id: 32, parent_id: 31, node_type: 'team', name: '招聘组', code: 'TEAM-REC-HR', title: null, sort_order: 1 },
  { id: 33, parent_id: 32, node_type: 'employee', name: '卫国', code: 'EMP-013', title: '招聘主管', sort_order: 1 },
  { id: 34, parent_id: 31, node_type: 'team', name: '薪酬组', code: 'TEAM-COMP', title: null, sort_order: 2 },
  { id: 35, parent_id: 34, node_type: 'employee', name: '蒋欣', code: 'EMP-014', title: '薪酬专员', sort_order: 1 },
  { id: 36, parent_id: 30, node_type: 'sub_department', name: '财务部', code: 'SUB-FIN', title: null, sort_order: 2 },
  { id: 37, parent_id: 36, node_type: 'team', name: '核算组', code: 'TEAM-ACCT', title: null, sort_order: 1 },
  { id: 38, parent_id: 37, node_type: 'employee', name: '沈腾', code: 'EMP-015', title: '会计', sort_order: 1 },
  { id: 39, parent_id: 1, node_type: 'department', name: '海外事业部', code: 'DEPT-OVS', title: null, sort_order: 4 },
  { id: 40, parent_id: 39, node_type: 'sub_department', name: '北美区', code: 'SUB-NA', title: null, sort_order: 1 },
  { id: 41, parent_id: 40, node_type: 'team', name: '旧金山办公室', code: 'TEAM-SFO', title: null, sort_order: 1 },
  { id: 42, parent_id: 41, node_type: 'employee', name: '林青', code: 'EMP-016', title: '区域负责人', sort_order: 1 },
]
