-- 组织架构权限树：表结构 + 种子数据
-- 支持无限层级嵌套：通过 parent_id 自引用实现 部门/子部门/小组/员工 任意深度

CREATE TABLE IF NOT EXISTS org_nodes (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  parent_id BIGINT UNSIGNED NULL,
  node_type VARCHAR(20) NOT NULL COMMENT 'department/sub_department/team/employee',
  name VARCHAR(100) NOT NULL,
  code VARCHAR(50) NULL,
  title VARCHAR(100) NULL,
  sort_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_parent (parent_id),
  KEY idx_type (node_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 种子数据：星辰科技集团（5 层嵌套，演示无限层级）
INSERT INTO org_nodes (id, parent_id, node_type, name, code, title, sort_order) VALUES
(1, NULL, 'department', '星辰科技集团', 'GROUP-001', NULL, 1),
(2, 1, 'department', '技术中心', 'DEPT-TECH', NULL, 1),
(3, 2, 'sub_department', '基础架构部', 'SUB-INFRA', NULL, 1),
(4, 3, 'team', '云平台组', 'TEAM-CLOUD', NULL, 1),
(5, 4, 'employee', '张伟', 'EMP-001', '云平台工程师', 1),
(6, 4, 'employee', '李娜', 'EMP-002', '云平台工程师', 2),
(7, 3, 'team', '运维组', 'TEAM-SRE', NULL, 2),
(8, 7, 'employee', '王强', 'EMP-003', '运维工程师', 1),
(9, 2, 'sub_department', '产品研发部', 'SUB-PROD', NULL, 2),
(10, 9, 'team', '前端组', 'TEAM-FE', NULL, 1),
(11, 10, 'employee', '陈思', 'EMP-004', '前端工程师', 1),
(12, 10, 'employee', '刘洋', 'EMP-005', '前端工程师', 2),
(13, 9, 'team', '后端组', 'TEAM-BE', NULL, 2),
(14, 13, 'employee', '赵敏', 'EMP-006', '后端工程师', 1),
(15, 13, 'employee', '孙浩', 'EMP-007', '后端工程师', 2),
(16, 2, 'sub_department', '算法实验室', 'SUB-ALGO', NULL, 3),
(17, 16, 'team', '推荐算法组', 'TEAM-REC', NULL, 1),
(18, 17, 'employee', '周婷', 'EMP-008', '算法工程师', 1),
(19, 16, 'team', '视觉算法组', 'TEAM-CV', NULL, 2),
(20, 19, 'employee', '吴磊', 'EMP-009', '算法工程师', 1),
(21, 1, 'department', '业务中心', 'DEPT-BIZ', NULL, 2),
(22, 21, 'sub_department', '销售部', 'SUB-SALES', NULL, 1),
(23, 22, 'team', '大客户组', 'TEAM-KEY', NULL, 1),
(24, 23, 'employee', '郑爽', 'EMP-010', '销售经理', 1),
(25, 22, 'team', '渠道组', 'TEAM-CH', NULL, 2),
(26, 25, 'employee', '冯巩', 'EMP-011', '销售代表', 1),
(27, 21, 'sub_department', '市场部', 'SUB-MKT', NULL, 2),
(28, 27, 'team', '品牌组', 'TEAM-BRAND', NULL, 1),
(29, 28, 'employee', '褚燕', 'EMP-012', '品牌经理', 1),
(30, 1, 'department', '职能中心', 'DEPT-FUNC', NULL, 3),
(31, 30, 'sub_department', '人力资源部', 'SUB-HR', NULL, 1),
(32, 31, 'team', '招聘组', 'TEAM-REC-HR', NULL, 1),
(33, 32, 'employee', '卫国', 'EMP-013', '招聘主管', 1),
(34, 31, 'team', '薪酬组', 'TEAM-COMP', NULL, 2),
(35, 34, 'employee', '蒋欣', 'EMP-014', '薪酬专员', 1),
(36, 30, 'sub_department', '财务部', 'SUB-FIN', NULL, 2),
(37, 36, 'team', '核算组', 'TEAM-ACCT', NULL, 1),
(38, 37, 'employee', '沈腾', 'EMP-015', '会计', 1),
(39, 1, 'department', '海外事业部', 'DEPT-OVS', NULL, 4),
(40, 39, 'sub_department', '北美区', 'SUB-NA', NULL, 1),
(41, 40, 'team', '旧金山办公室', 'TEAM-SFO', NULL, 1),
(42, 41, 'employee', '林青', 'EMP-016', '区域负责人', 1);
